name: Unity-Actions

on:
    pull_request: {}
    push: { branches: [master] }

env:
    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
    test-edit-mode:
        name: Edit Mode Tests
        runs-on: self-hosted
        steps:
            #Checkout repo
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                lfs: true

            #Run Unity Tests
            - name: Run Unity EditMode Tests
              run: C:\"Program Files"\Unity\Hub\Editor\2019.4.11f1\Editor\Unity.exe -batchmode -nographics -projectPath . -runTests -testPlatform editmode -logFile -testResults .\unit-tests.xml -quit
              shell: cmd
    build:
        name: build
        runs-on: self-hosted
        steps:
            - run: echo 'Build'
              shell: cmd
    deploy:
        name: deploy
        runs-on: self-hosted
        steps:
            - run: echo 'Deploy'
              shell: cmd