name: Unity-Actions

on:
    pull_request: {}
    push: { branches: [master] }

env:
    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

stages:
    - stage: test
      jobs:
        test-edit-mode:
            name: Edit Mode Tests
            runs-on: self-hosted
            steps:
                run: echo 'Test'
                shell: cmd
    - stage: build
      jobs:
        build:
            name: build
            run: echo 'Build'
            shell: bash
    - stage: deploy
      jobs:
        build:
            name: deploy
            run: echo 'Deploy'
            shell: bash