name: Unity-Actions

on:
    pull_request: {}
    push: { branches: [master] }

env:
    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
    test-edit-mode:
        name: Edit Mode Tests
        runs-on: self-hosted
        steps:
            - run: C:\"Program Files"\Unity\Hub\Editor\2019.4.11f1\Editor\Unity.exe -batchmode -nographics -projectPath "https://github.com/sorainsm/Game-PhDev/tree/master/Go-Nogo-Task" -runTests -testPlatform editmode -logFile -testResults .\unit-tests.xml -quit
              shell: cmd
    build:
        name: build
        runs-on: self-hosted
        steps:
            - run: echo 'Build'
              shell: cmd
    deploy:
        name: deploy
        runs-on: self-hosted
        steps:
            - run: echo 'Deploy'
              shell: cmd