name: Actions

on:
    pull_request: {}
    push: { branches: [master] }

env:
    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

stages:
    - stage: test
      jobs:
        test-edit-mode:
            name: Edit Mode Tests
            runs-on: self-hosted
            steps:
                script: "C:\Program Files\Unity\Hub\Editor\2019.4.11f1\Editor\Unity.exe -batchmode -nographics -projectPath . -runTests -testPlatform editmode -logFile -testResults ./unity-tests.xml"
    - stage: build
      jobs:
        build:
            name: build
            script: "echo 'Build'"
    - stage: deploy
      jobs:
        build:
            name: deploy
            script: "echo 'Deploy'"