name: Unity-Actions

on:
    pull_request: {}
    push: { branches: [master] }

env:
    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
    UNITY_LOCATION: C:\"Program Files"\Unity\Hub\Editor\2020.1.6f1\Editor\Unity.exe

jobs:
    tests:
        name: Run Tests
        runs-on: self-hosted
        steps:
            #Checkout repo
            - name: Checkout repository
              uses: actions/checkout@v2.3.3
              with:
                lfs: true

            #Make a directory to save artifacts in
            - name: Make directory for log file and test outputs
              run: mkdir TestLog
              shell: cmd

            #Run Unity Tests
            - name: Run Unity EditMode Tests
              run: ${{UNITY_LOCATION}} -batchmode -projectPath Go-Nogo-Task\ -runTests -testPlatform editmode -testResults TestLog\editmode-tests.xml -logFile TestLog\editmode.log
              shell: cmd

            #Run Unity Playmode tests
            - name: Run Unity Playmode Tests
              run: ${{UNITY_LOCATION}} -batchmode -projectPath Go-Nogo-Task\ -runTests -testPlatform playmode -testResults TestLog\playmode-tests.xml -logFile TestLog\playmode.log

            #Upload artifact
            - name: Upload test outputs
              uses: actions/upload-artifact@v2
              with:
                name: logs
                path: .\TestLog
    build:
        name: build
        runs-on: self-hosted
        steps:
            - run: echo 'Build'
              shell: cmd
    deploy:
        name: deploy
        runs-on: self-hosted
        steps:
            - run: echo 'Deploy'
              shell: cmd