name: Unity-Actions

on:
    pull_request: {}
    push: { branches: [master] }

env:
    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
    test-edit-mode:
        name: Edit Mode Tests
        runs-on: self-hosted
        steps:
            - run: echo 'Test'
              shell: cmd
    build:
        name: build
        runs-on: self-hosted
        steps:
            - run: echo 'Build'
              shell: cmd
    deploy:
        name: deploy
        runs-on: self-hosted
        steps:
            - run: echo 'Deploy'
              shell: cmd